### ISSUE TITLE
Question: Waze Engine API

### ISSUE THREAD

**Issue by aspeddro** [gabriel-milan/geolocate#5]
The docstring of the `WazeEngine` class says that it is used to geolocate an address.

The request is made at:
https://github.com/gabriel-milan/geolocate/blob/96e0f015f6de8585d84dec4135b1e2eb4f30005f/geolocate/engines.py#L249-L261

On a quick inspection of the site `https://www.waze.com/en-BR/live-map/`, the API is used for autocomplete.

Is this API documented? Maybe it should be explicit that the API use `autocomplete` endpoint?

**Comment by gabriel-milan** [comment]
Greetings!

> API is used for autocomplete.

Yes, this endpoint is originally used for autocomplete, but the response has enough data to georeference an address.




> Is this API documented? Maybe it should be explicit that the API use `autocomplete` endpoint?

I'm not sure it's documented, to be honest. Why do you think this should be explicit?

**Comment by maxbernal7** [comment]
hi It seems the engine does not work anymore, Run it but I obtaint this message

![image](https://user-images.githubusercontent.com/30870373/209408899-c7ce13fb-2c3a-461d-91fe-0400fb5597ed.png)

any ideas how to fix this ?

**Comment by gabriel-milan** [comment]
> any ideas how to fix this ?

They seem to have deprecated this endpoint. In order to fix this in the package, we need to implement new engines one could use. The currently implemented `WazeEngine` will no longer work.

**Comment by maxbernal7** [comment]
found some avaliabe but all of them needs some others parameters (as api key in google maps)

**Comment by aspeddro** [comment]
> I'm not sure it's documented, to be honest. Why do you think this should be explicit?

Because it can be a non-dedicated endpoint for geocoding, they are different mechanisms.

**Comment by gabriel-milan** [comment]
The docstring refers to the class itself, and it is used for geocoding, so I don't think that anything is really missing. The underlying implementation indeed used to fetch from the autocomplete API, though. Maybe it's a good idea we add it to the docstring, feel free to open a PR on that, although the `WazeEngine` implementation is no longer working (it seems like they've deprecated this endpoint). Also, for that reason, I'm closing this issue.
